version: '3'

services:
   api:
        image: ${API_IMAGE:-odh-tourism-api}:${API_TAG-latest}
        build:
          context: .
          dockerfile: OdhApiCore/Dockerfile
        restart: unless-stopped
