version: '3.4'

services:
  api:
    image: ${DOCKER_IMAGE_API:-odh-tourism-api}:${DOCKER_TAG_API:-latest}
    build:
      context: .
      dockerfile: OdhApiCore/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ConnectionStrings__PgConnection: ${PG_CONNECTION}
    ports:
      - "60209:80"
